### ISSUE TITLE
Basic example fails with `TypeError: this.duplex.writable.abort is not a function`

### ISSUE THREAD

**Issue by radekbenkel** [supabase-community/pg-gateway#22]
# Bug report

## Describe the bug

Actually, error is the same when using `pglite` example, that's why I tried simpler one. 

When I will run basic example and try to connect to exposed TCP I'm getting following error: 

```shell
Server listening on port 5432
TypeError: A.writable.getWriter is not a function
    at BA.processData (file:///gateway/node_modules/pg-gateway/dist/chunk-HI3RLAFM.js:1:206802)
    at BA.init (file:///gateway/node_modules/pg-gateway/dist/chunk-HI3RLAFM.js:1:205896)
    at new BA (file:///gateway/node_modules/pg-gateway/dist/chunk-HI3RLAFM.js:1:205518)
    at Server.<anonymous> (file:///gateway/server.mjs:7:22)
    at Server.emit (node:events:519:28)
    at TCP.onconnection (node:net:2204:8)
file:///gateway/node_modules/pg-gateway/dist/chunk-HI3RLAFM.js:1

# lot of minified code

TypeError: this.duplex.writable.abort is not a function
    at BA.init (file:///gateway/node_modules/pg-gateway/dist/chunk-HI3RLAFM.js:1:206692)
```

## To Reproduce

1. Create project and install required packages: `npm init -y && npm install pg-gateway`
1. Copy first example from [usage](https://github.com/supabase-community/pg-gateway?tab=readme-ov-file#usage) to file `server.mjs`
1. Run server in one tab `node server.mjs`
1. In second tab run `psql -h localhost`, `node` process will exit with previously mentioned message and `psql` with: 

```
psql: error: connection to server at "localhost" (::1), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

Similar behavior with `pgcli`: 

```
connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
```

## Expected behavior

Lack of error :)

## System information

- OS: Alpine Linux v3.20.3running in container via Docker, version 3.20.3 (aarch64)
- Version of pg-gateway: 0.3.0-beta.3
- Version of Node.js: 20.15.1

**Comment by radekbenkel** [comment]
OK, turns out I was using documentation from `main` branch to code from `0.3.0-beta.3` tag (which as actually never than `main`). 

Closing :)
